---
- hosts: ws
  become: yes
  tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Remove useless packages
      ansible.builtin.apt:
        autoclean: yes

    - name: Remove Dependencies no longer needed
      ansible.builtin.apt:
        autoremove: yes    

